// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type udpUdpKey struct {
	_      structs.HostLayout
	Family uint8
	Pad    [3]uint8
	Saddr  [4]uint32
	Daddr  [4]uint32
	Sport  uint16
	Dport  uint16
}

type udpUdpVal struct {
	_  structs.HostLayout
	Tx uint64
	Rx uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	udpMapUdpBytes    = "udp_bytes"
	udpProgUdpConsume = "udp_consume"
	udpProgUdpSend    = "udp_send"
	udpProgUdpv6Send  = "udpv6_send"
)

// loadUdp returns the embedded CollectionSpec for udp.
func loadUdp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UdpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load udp: %w", err)
	}

	return spec, err
}

// loadUdpObjects loads udp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*udpObjects
//	*udpPrograms
//	*udpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadUdpObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadUdp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// udpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udpSpecs struct {
	udpProgramSpecs
	udpMapSpecs
	udpVariableSpecs
}

// udpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udpProgramSpecs struct {
	UdpConsume *ebpf.ProgramSpec `ebpf:"udp_consume"`
	UdpSend    *ebpf.ProgramSpec `ebpf:"udp_send"`
	Udpv6Send  *ebpf.ProgramSpec `ebpf:"udpv6_send"`
}

// udpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udpMapSpecs struct {
	UdpBytes *ebpf.MapSpec `ebpf:"udp_bytes"`
}

// udpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type udpVariableSpecs struct {
}

// udpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadUdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type udpObjects struct {
	udpPrograms
	udpMaps
	udpVariables
}

func (o *udpObjects) Close() error {
	return _UdpClose(
		&o.udpPrograms,
		&o.udpMaps,
	)
}

// udpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadUdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type udpMaps struct {
	UdpBytes *ebpf.Map `ebpf:"udp_bytes"`
}

func (m *udpMaps) Close() error {
	return _UdpClose(
		m.UdpBytes,
	)
}

// udpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadUdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type udpVariables struct {
}

// udpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadUdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type udpPrograms struct {
	UdpConsume *ebpf.Program `ebpf:"udp_consume"`
	UdpSend    *ebpf.Program `ebpf:"udp_send"`
	Udpv6Send  *ebpf.Program `ebpf:"udpv6_send"`
}

func (p *udpPrograms) Close() error {
	return _UdpClose(
		p.UdpConsume,
		p.UdpSend,
		p.Udpv6Send,
	)
}

func _UdpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed udpbpf_x86_bpfel.o
var _UdpBytes []byte
